// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcPm4kF0sN6yLaDf4oNz3capJz3CuXrHA',
    appId: '1:495403715507:web:034b1027c6784151a299c6',
    messagingSenderId: '495403715507',
    projectId: 'patelvasudevnareshbhai',
    authDomain: 'patelvasudevnareshbhai.firebaseapp.com',
    storageBucket: 'patelvasudevnareshbhai.firebasestorage.app',
    measurementId: 'G-SHV23FZY02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPe8LTKad5lJq-iCtLAMK9KinWbXWdW9k',
    appId: '1:495403715507:android:5f06fbabcfcec4faa299c6',
    messagingSenderId: '495403715507',
    projectId: 'patelvasudevnareshbhai',
    storageBucket: 'patelvasudevnareshbhai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCBZ-LDzSCyS_8aHBD8XlkV4-qzK3HN0I',
    appId: '1:495403715507:ios:62b71b06b94c4cb6a299c6',
    messagingSenderId: '495403715507',
    projectId: 'patelvasudevnareshbhai',
    storageBucket: 'patelvasudevnareshbhai.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCBZ-LDzSCyS_8aHBD8XlkV4-qzK3HN0I',
    appId: '1:495403715507:ios:62b71b06b94c4cb6a299c6',
    messagingSenderId: '495403715507',
    projectId: 'patelvasudevnareshbhai',
    storageBucket: 'patelvasudevnareshbhai.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcPm4kF0sN6yLaDf4oNz3capJz3CuXrHA',
    appId: '1:495403715507:web:871ea88e9e4ece40a299c6',
    messagingSenderId: '495403715507',
    projectId: 'patelvasudevnareshbhai',
    authDomain: 'patelvasudevnareshbhai.firebaseapp.com',
    storageBucket: 'patelvasudevnareshbhai.firebasestorage.app',
    measurementId: 'G-GDYPKHLTY5',
  );
}
